name: flutter_device_locale
description: A Flutter plugin for retrieving the device locale information.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:

  plugin:
    androidPackage: io.leadcode.flutter_device_locale
    pluginClass: FlutterDeviceLocalePlugin
